### ISSUE TITLE
Edge Router listeners cannot use different advertiser hostnames

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/edge#1103]
*Experienced*

Attempting to configure an edge router for SNI for the same binding but different protocols, the Edge Router will not allow two different hostnames.

*Expected* 

Allow any number of hostnames for listener advertisements.

*Reproduction*

```
listeners:
- binding: edge
  address: tls:0.0.0.0:8080
  options:
    advertise: 127.0.0.1:8080
- binding: edge
  address: ws:0.0.0.0:443
  options:
    advertise: mydomain.com:443
```
